Topic/collision
proyan/crocoddyl pull request #2
Opened 2020-09-18 13:33 UTC by ksyy

PR for discussing the ongoing implementation of the collision code.

2020-09-18 13:38 UTC, proyan commented
I'll rebase the branch on the current devel

2020-09-18 13:56 UTC, proyan requested changes

2020-09-18 13:56 UTC, proyan commented on bindings/python/crocoddyl/core/activations/collision.cpp
> +// Copyright (C) 2018-2020, LAAS-CNRS, University of Edinburgh
You should change the year to 2020, and remove Univ of Edinburgh from here.

2020-09-18 13:56 UTC, proyan commented on bindings/python/crocoddyl/multibody/costs/pair-collision.cpp
> +// Copyright (C) 2018-2020, LAAS-CNRS, University of Edinburgh
Same here.

2020-09-18 13:56 UTC, proyan commented on include/crocoddyl/core/activations/collision.hpp
> +// Copyright (C) 2018-2020, LAAS-CNRS, University of Edinburgh
Same here

2020-09-18 13:56 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +// Copyright (C) 2018-2020, LAAS-CNRS, University of Edinburgh
Same

2020-09-18 13:56 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::computeDistances(pin_model, pin_data, geom_model_, geom_data_, q);
Why are you using this signature and not the following for a single pair?
```c++                       
  ///                                                                                                                                                                                         
  /// \brief Compute the minimal distance between collision objects of a *SINGLE* collison pair                                                                                               
  ///                                                                                                                                                                                         
  /// \param[in] GeomModel the geometry model (const)                                                                                                                                         
  /// \param[out] GeomData the corresponding geometry data, where computations are done.                                                                                                      
  /// \param[in] pairId The index of the collision pair in geom model.                                                                                                                        
  ///                                                                                                                                                                                         
  /// \return A reference on fcl struct containing the distance result, referring an element                                                                                                  
  /// of vector geom_data::distanceResults.                                                                                                                                                   
  /// \note The complete distance result is also available in geom_data.distanceResults[pairId]                                                                                               
  ///                                                                                                                                                                                         
  fcl::DistanceResult & computeDistance(const GeometryModel & geom_model,                                                                                                                     
                                        GeometryData & geom_data,                                                                                                                             
                                        const PairIndex & pairId);                                                                                                                            
```

2020-09-21 08:45 UTC, nmansard approved these changes

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +  explicit ActivationModelCollisionTpl(const std::size_t nr, const Scalar threshold = 0.3) :
The threshold corresponds to the barrier of activation. It should be exposed in the API (both C++ and Python) following the same pattern as activation.lower and activation.upper in the quadratic-barrier activation.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +  explicit ActivationModelCollisionTpl(const std::size_t nr, const Scalar threshold = 0.3) :
the name of class and file activation/collision is not great. There is nothing specific to collision here. Let's try to find something more explicit. 
- ActivationModelGreaterThanNorm2 ?
- ActivationModelNorm2Barrier ?

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +    if (static_cast<std::size_t>(r.size()) != nr_) {
How is it important to know the size of the residual nr? This is a useless check and complexification. The activation function does not need to be aware of the size of the residual it should expect.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +  Scalar distance_;
distance is part of data, not of model. Relocate it in data.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +      data->Arr.diagonal() = (MatrixXs::Identity(nr_, nr_) * (distance_ - threshold_) / distance_ +
this is not an efficient way of allocating the diagonal. do something similar without creating an Identity matrix on the flight, by working with vectors. See smoothAbs activation for an example.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +  pinocchio::GeometryData& geom_data_;
this should be part of data, relocate it in data.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +  const pinocchio::PairIndex pair_id_;
on the long term, this should be removed as all pairs of the geom model will be handle in the cost function. It is ok to keep it in the short term, but mention to the temporary aspect should be added in comment.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +                          const pinocchio::JointIndex joint_id); // Used to calculate the Jac at the joint
this information is stored in the geomModel. Why passing it as a redundant argument here?

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +                          pinocchio::GeometryData& geom_data,
not in argument, see below #64.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +    // Check that proper shared data has been passed
in the short term, I think it is fair to allocate here a new geomData. If the user wants his own data instead of a newly-created one, he can give the pointer afterward.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +  Vector3s p1_; // Used by calcDiff
same here: p1_ is a data, relocate it in data.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::computeDistances(pin_model, pin_data, geom_model_, geom_data_, q);
In the long term, all distances for the given geometry model should be computed and put in the cost. In the short term, I agree, although it should not change much if the user is smart enough to give a model with a single a collision pair.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto& d  = *static_cast<Data*>(data.get());
outside of the discussion about C++11 in crocoddyl, auto typing should be chosen when making a trade-off between type complexity, locality of the variable context, and debug status (i.e. auto is ok for a variable that is limited to a super small context, with a super ugly type --like the one due to CRTP in eigen-- and not to stay in the code on the long term; on the opposite, it should not be used when the type is simple --like Data&--, the variable is used in the full function context and it is made to stay for all future version of the code).

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  p1_ = distance_result.nearest_points[0];
why are you copying this info in the data? Maintaining a const reference to it is sufficient (the reference can be re-made if you want in calcDiff).

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto p2 = distance_result.nearest_points[1];
no reason to copy here, you can simply make a const ref.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::computeJointJacobians(pin_model, pin_data, q); // Needed by getJointJacobian
this is already done in the DAModel. No need to ask it to be recomputed in the costModel.
@proyan please confirm.

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::updateFramePlacements(pin_model, pin_data);
same remark as line  76

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  typename std::remove_reference_t<decltype(pin_data)>::Matrix6x J(6, pin_model.nv);
The type is super complex. Why?
This variable should be allocated in data, not on the flight. See the other cost models, e.g. frame-translation for an example

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d.J = J.topRows(3) + pinocchio::skew(p1_local_world).transpose() * (J.bottomRows(3));
just for the reference: following the code of Teguh, this jacobian only works when the second object P2 is attached to the universe. It is not going to work if trying to do auto-collision.
@edantec: is that clear for you?

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d.Rx << d.J, MatrixXs::Zero(activation_->get_nr(), state_->get_nv());
<< is unefficient in eigen. 
No need to reset the 0 subpart of the matrix (just do it at initialization).

2020-09-21 08:45 UTC, nmansard commented on include/crocoddyl/core/activations/collision.hpp
> +    if (static_cast<std::size_t>(r.size()) != nr_) {
This is important for constructing Ar and Arr. It is likely we cannot avoid it. Too bad, but ok, forget about my comment.

2020-09-23 09:48 UTC, ksyy commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto& d  = *static_cast<Data*>(data.get());
I disagree. `auto` should be used wherever possible, especially in this case where the type is already mentioned in the cast.
Also, it eases the burden of maintainability in the future, even if at the moment, there is no plan to change this type.
Using a proper IDE will yield the real type to the people using this code.

2020-09-23 10:35 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto& d  = *static_cast<Data*>(data.get());
@ksyy I understand your point, but when you are contributing to a work involving multiple members, it is not always possible to accommodate personal coding choices. We have not made this choice in crocoddyl, and since you are developing on top of the code (and not creating an independent piece of work), it should conform to the code that you are using.

2020-09-23 10:36 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::computeJointJacobians(pin_model, pin_data, q); // Needed by getJointJacobian
yes. you should remove this.

2020-09-23 10:41 UTC, ksyy commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto& d  = *static_cast<Data*>(data.get());
Yes, of course, the change has been made. 
But this is a space for discussion, so I used it to discuss my point of view =)

2020-09-24 16:39 UTC, ksyy commented on include/crocoddyl/core/activations/collision.hpp
> +  explicit ActivationModelCollisionTpl(const std::size_t nr, const Scalar threshold = 0.3) :
Implemented in [a0d22a3](https://github.com/proyan/crocoddyl/pull/2/commits/a0d22a3a5c5099fcb9fae29a8cf96e763f16c36c)

2020-09-24 17:06 UTC, ksyy commented on include/crocoddyl/core/activations/collision.hpp
> +  explicit ActivationModelCollisionTpl(const std::size_t nr, const Scalar threshold = 0.3) :
I went with **ActivationModelNorm2Barrier** in 6693b90

2020-09-25 12:34 UTC, edantec commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d.J = J.topRows(3) + pinocchio::skew(p1_local_world).transpose() * (J.bottomRows(3));
I think yes. The Jacobian at p1 is the same as the jacobian of the joint except that we have to take into account the translation from the joint to p1.

2020-09-25 12:35 UTC, edantec commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  typename std::remove_reference_t<decltype(pin_data)>::Matrix6x J(6, pin_model.nv);
Just to add that I couldn't compile that with std::remove_reference_t but it worked with boost::remove_reference_t

2020-09-25 12:42 UTC, edantec commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::computeDistances(pin_model, pin_data, geom_model_, geom_data_, q);
I think for the first try on the robot next week, we better compute the cost for just one collision pair to reduce runtime computation as much as possible

2020-09-25 16:28 UTC, proyan commented
I've done minor changes till now, I'll rework this in the evening

2020-09-28 09:41 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +                          pinocchio::GeometryData& geom_data,
done

2020-09-28 09:42 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +    // Check that proper shared data has been passed
done.

2020-09-28 09:42 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +  Vector3s p1_; // Used by calcDiff
done.

2020-09-28 09:48 UTC, proyan commented on include/crocoddyl/core/activations/collision.hpp
> +  Scalar distance_;
done.

2020-09-28 09:49 UTC, proyan commented on include/crocoddyl/core/activations/collision.hpp
> +      data->Arr.diagonal() = (MatrixXs::Identity(nr_, nr_) * (distance_ - threshold_) / distance_ +
done.

2020-09-28 09:49 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +  pinocchio::GeometryData& geom_data_;
done.

2020-09-28 09:51 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hpp
> +                          const pinocchio::JointIndex joint_id); // Used to calculate the Jac at the joint
What do you mean? `joint_id` is not stored in geomModel.

2020-09-28 09:52 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto& d  = *static_cast<Data*>(data.get());
for now, this is changed to previous style.

2020-09-28 09:52 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  auto p2 = distance_result.nearest_points[1];
done.

2020-09-28 09:53 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  typename std::remove_reference_t<decltype(pin_data)>::Matrix6x J(6, pin_model.nv);
updated this part.

2020-09-28 09:54 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d.J = J.topRows(3) + pinocchio::skew(p1_local_world).transpose() * (J.bottomRows(3));
I resolve this.

2020-09-28 09:54 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d.Rx << d.J, MatrixXs::Zero(activation_->get_nr(), state_->get_nv());
changed.

2020-09-28 09:55 UTC, proyan commented on include/crocoddyl/core/activations/collision.hpp
> +  explicit ActivationModelCollisionTpl(const std::size_t nr, const Scalar threshold = 0.3) :
`ActivationModelNorm2Barrier` and `ActivationModelQuadraticBarrier` are inside/outside versions of a similar activation model, we need to be more informative, but I can't think of something.

2020-09-28 14:21 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  p1_ = distance_result.nearest_points[0];
done.

2020-09-28 14:21 UTC, proyan commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  pinocchio::updateFramePlacements(pin_model, pin_data);
done.

2020-09-28 16:57 UTC, nmansard commented on include/crocoddyl/multibody/costs/pair-collisions.hxx
> +  d->J.template topRows<3>().noalias() += pinocchio::skew(p1_local_world).transpose() * (d->J.template bottomRows<3>());
could we try two modifications here (benchmark it, not sure they are better):
- remove skew*J  rather than add skew.T*J (skew is antisymetrical)
- due the J[:3] - skew*J[3:]  operation directly in the Rx matrix, rather than doing it inside J and then copying it to Rx.

skew*J is indeed a big matrix operation that we have to pay for each single collision pair. That is expensive. Is that the most efficient way of doing it?

2020-10-15 20:52 UTC, proyan commented
I've rebased this branch on top of devel

2020-10-15 20:55 UTC, merged